import path from "path"
import { fileURLToPath } from "url"
import fs from "fs"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"

// Fetch and generate models.dev snapshot
let modelsData: string

if (process.env.MODELS_DEV_API_JSON) {
  // Use local file if specified
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  console.log("Using local models API JSON from:", process.env.MODELS_DEV_API_JSON)
} else if (process.env.SKIP_MODELS_FETCH === "true") {
  // Skip fetch if explicitly disabled
  if (fs.existsSync(snapshotPath)) {
    console.log("Skipping models fetch (SKIP_MODELS_FETCH=true), using existing snapshot")
  } else {
    console.log("Skipping models fetch (SKIP_MODELS_FETCH=true), using empty snapshot")
    modelsData = "{}"
  }
} else {
  // Try to fetch, but fallback to existing file or empty object if it fails
  try {
    modelsData = await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
    console.log("Fetched models snapshot from:", modelsUrl)
  } catch (error) {
    console.warn("⚠️  Failed to fetch models snapshot:", error.message)
    if (fs.existsSync(snapshotPath)) {
      console.log("Using existing models-snapshot.js")
    } else {
      console.log("Using empty snapshot as fallback")
      modelsData = "{}"
    }
  }
}

if (modelsData) {
  await Bun.write(
    snapshotPath,
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
}
