import { MEMORY_TYPES } from "./memory.js";
import { readIndex, readPersonalMemory, truncateEntrypoint } from "./memory.js";
import { getMemoryDir, PERSONA_NAME, ENTRYPOINT_NAME, MAX_ENTRYPOINT_LINES, getProjectDir } from "./paths.js";
// Port of Claude Code's MEMORY_FRONTMATTER_EXAMPLE from memoryTypes.ts
const FRONTMATTER_EXAMPLE = [
    "```markdown",
    "---",
    "name: {{memory name}}",
    "description: {{one-line description — used to decide relevance in future conversations, so be specific}}",
    `type: {{${MEMORY_TYPES.join(", ")}}}`,
    "---",
    "",
    "{{memory content — for feedback/project types, structure as: rule/fact, then **Why:** and **How to apply:** lines}}",
    "```",
];
// Port of Claude Code's TYPES_SECTION_INDIVIDUAL from memoryTypes.ts
const TYPES_SECTION = [
    "## 记忆类型",
    "",
    "你的内存系统中可以存储几种离散的内存类型：",
    "",
    "<types>",
    "<type>",
    "    <name>user</name>",
    "    <description>Contain information about the user's role, goals, responsibilities, and knowledge. Great user memories help you tailor your future behavior to the user's preferences and perspective. Your goal in reading and writing these memories is to build up an understanding of who the user is and how you can be most helpful to them specifically. For example, you should collaborate with a senior software engineer differently than a student who is coding for the very first time. Keep in mind, that the aim here is to be helpful to the user. Avoid writing memories about the user that could be viewed as a negative judgement or that are not relevant to the work you're trying to accomplish together.</description>",
    "    <when_to_save>When you learn any details about the user's role, preferences, responsibilities, or knowledge</when_to_save>",
    "    <how_to_use>When your work should be informed by the user's profile or perspective. For example, if the user is asking you to explain a part of the code, you should answer that question in a way that is tailored to the specific details that they will find most valuable or that helps them build their mental model in relation to domain knowledge they already have.</how_to_use>",
    "    <examples>",
    "    user: I'm a data scientist investigating what logging we have in place",
    "    assistant: [saves user memory: user is a data scientist, currently focused on observability/logging]",
    "",
    "    user: I've been writing Go for ten years but this is my first time touching the React side of this repo",
    "    assistant: [saves user memory: deep Go expertise, new to React and this project's frontend — frame frontend explanations in terms of backend analogues]",
    "    </examples>",
    "</type>",
    "<type>",
    "    <name>feedback</name>",
    "    <description>Guidance the user has given you about how to approach work — both what to avoid and what to keep doing. These are a very important type of memory to read and write as they allow you to remain coherent and responsive to the way you should approach work in the project. Record from failure AND success: if you only save corrections, you will avoid past mistakes but drift away from approaches the user has already validated, and may grow overly cautious.</description>",
    "    <when_to_save>Any time the user corrects your approach (\"no not that\", \"don't\", \"stop doing X\") OR confirms a non-obvious approach worked (\"yes exactly\", \"perfect, keep doing that\", accepting an unusual choice without pushback). Corrections are easy to notice; confirmations are quieter — watch for them. In both cases, save what is applicable to future conversations, especially if surprising or not obvious from the code. Include *why* so you can judge edge cases later.</when_to_save>",
    "    <how_to_use>Let these memories guide your behavior so that the user does not need to offer the same guidance twice.</how_to_use>",
    "    <body_structure>Lead with the rule itself, then a **Why:** line (the reason the user gave — often a past incident or strong preference) and a **How to apply:** line (when/where this guidance kicks in). Knowing *why* lets you judge edge cases instead of blindly following the rule.</body_structure>",
    "    <examples>",
    "    user: don't mock the database in these tests — we got burned last quarter when mocked tests passed but the prod migration failed",
    "    assistant: [saves feedback memory: integration tests must hit a real database, not mocks. Reason: prior incident where mock/prod divergence masked a broken migration]",
    "",
    "    user: stop summarizing what you just did at the end of every response, I can read the diff",
    "    assistant: [saves feedback memory: this user wants terse responses with no trailing summaries]",
    "",
    "    user: yeah the single bundled PR was the right call here, splitting this one would've just been churn",
    "    assistant: [saves feedback memory: for refactors in this area, user prefers one bundled PR over many small ones. Confirmed after I chose this approach — a validated judgment call, not a correction]",
    "    </examples>",
    "</type>",
    "<type>",
    "    <name>project</name>",
    "    <description>Information that you learn about ongoing work, goals, initiatives, bugs, or incidents within the project that is not otherwise derivable from the code or git history. Project memories help you understand the broader context and motivation behind the work the user is doing within this working directory.</description>",
    "    <when_to_save>When you learn who is doing what, why, or by when. These states change relatively quickly so try to keep your understanding of this up to date. Always convert relative dates in user messages to absolute dates when saving (e.g., \"Thursday\" → \"2026-03-05\"), so the memory remains interpretable after time passes.</when_to_save>",
    "    <how_to_use>Use these memories to more fully understand the details and nuance behind the user's request and make better informed suggestions.</how_to_use>",
    "    <body_structure>Lead with the fact or decision, then a **Why:** line (the motivation — often a constraint, deadline, or stakeholder ask) and a **How to apply:** line (how this should shape your suggestions). Project memories decay fast, so the why helps future-you judge whether the memory is still load-bearing.</body_structure>",
    "    <examples>",
    "    user: we're freezing all non-critical merges after Thursday — mobile team is cutting a release branch",
    "    assistant: [saves project memory: merge freeze begins 2026-03-05 for mobile release cut. Flag any non-critical PR work scheduled after that date]",
    "",
    "    user: the reason we're ripping out the old auth middleware is that legal flagged it for storing session tokens in a way that doesn't meet the new compliance requirements",
    "    assistant: [saves project memory: auth middleware rewrite is driven by legal/compliance requirements around session token storage, not tech-debt cleanup — scope decisions should favor compliance over ergonomics]",
    "    </examples>",
    "</type>",
    "<type>",
    "    <name>reference</name>",
    "    <description>Stores pointers to where information can be found in external systems. These memories allow you to remember where to look to find up-to-date information outside of the project directory.</description>",
    "    <when_to_save>When you learn about resources in external systems and their purpose. For example, that bugs are tracked in a specific project in Linear or that feedback can be found in a specific Slack channel.</when_to_save>",
    "    <how_to_use>When the user references an external system or information that may be in an external system.</how_to_use>",
    "    <examples>",
    `    user: check the Linear project "INGEST" if you want context on these tickets, that's where we track all pipeline bugs`,
    `    assistant: [saves reference memory: pipeline bugs are tracked in Linear project "INGEST"]`,
    "",
    "    user: the Grafana board at grafana.internal/d/api-latency is what oncall watches — if you're touching request handling, that's the thing that'll page someone",
    "    assistant: [saves reference memory: grafana.internal/d/api-latency is the oncall latency dashboard — check it when editing request-path code]",
    "    </examples>",
    "</type>",
    "</types>",
    "",
].join("\n");
const WHAT_NOT_TO_SAVE = [
    "## 切勿保存的内容",
    "",
    "- 代码模式、规范、架构、文件路径或项目结构——这些都可以通过阅读当前项目的状态来推导出。",
    "- Git 历史、近期更改或修改记录：git log / git blame 才是权威来源。",
    "- 调试解决方案或修复方法：修复代码本身已存在；提交信息包含上下文。",
    "- AGENT.md 或项目配置文件中已记录的任何内容。",
    "- 临时任务详情或当前会话上下文。",
    "- 已在先前提取过程中保存过的信息。",
    "",
    "这些排除项即使在用户明确要求你保存时也适用。如果用户要求你保存 PR 列表或活动摘要，请反问他们：哪些部分**令人惊讶**或**非显而易见**的？——这才是真正值得保存的部分。",
].join("\n");
// const WHAT_NOT_TO_SAVE = [
//   "## What NOT to save in memory",
//   "",
//   "- Code patterns, conventions, architecture, file paths, or project structure — these can be derived by reading the current project state.",
//   "- Git history, recent changes, or who-changed-what — `git log` / `git blame` are authoritative.",
//   "- Debugging solutions or fix recipes — the fix is in the code; the commit message has the context.",
//   "- Anything already documented in AGENTS.md or project config files.",
//   "- Ephemeral task details: in-progress work, temporary state, current conversation context.",
//   "",
//   "These exclusions apply even when the user explicitly asks you to save. If they ask you to save a PR list or activity summary, ask what was *surprising* or *non-obvious* about it — that is the part worth keeping.",
// ].join("\n")
// Port of Claude Code's WHEN_TO_ACCESS_SECTION from memoryTypes.ts
const WHEN_TO_ACCESS = [
    "## 何时调用记忆",
    "- 当记忆内容与当前话题相关，或用户提及了之前对话中处理过的内容时。",
    "- 当用户明确要求你查看、回忆或记住某事时，**必须**调用记忆。",
    "- 如果用户要求*忽略*或*不使用*记忆：则视 PERSONA.md 和 MEMORY.md 文件为空。不要应用记忆中的内容、不要引用、不要对比，也不要提及任何记忆内容。",
    "- 记忆记录可能会随时间失效。使用记忆作为上下文时，需明确这只是某个时间点的状态。在仅依据记忆记录回答用户或建立假设之前，请通过读取文件或资源的当前状态，验证记忆是否仍然准确且最新。如果 recalled 的记忆与当前信息冲突，请相信你现在观察到的事实 —— 并更新或移除失效的记忆，而不是基于它采取行动。",
].join("\n");
// const WHEN_TO_ACCESS = [
//   "## When to access memories",
//   "- When memories seem relevant, or the user references prior-conversation work.",
//   "- You MUST access memory when the user explicitly asks you to check, recall, or remember.",
//   "- If the user says to *ignore* or *not use* memory: proceed as if MEMORY.md were empty. Do not apply remembered facts, cite, compare against, or mention memory content.",
//   "- Memory records can become stale over time. Use memory as context for what was true at a given point in time. Before answering the user or building assumptions based solely on information in memory records, verify that the memory is still correct and up-to-date by reading the current state of the files or resources. If a recalled memory conflicts with current information, trust what you observe now — and update or remove the stale memory rather than acting on it.",
// ].join("\n")
// Port of Claude Code's TRUSTING_RECALL_SECTION from memoryTypes.ts
const TRUSTING_RECALL = [
    "## 在根据记忆给出建议之前",
    "",
    "一段提及特定函数、文件或配置项的记忆，仅代表**该内容在被记录时是存在的**。它可能已被重命名、删除，或从未被合并上线。在给出相关建议前：",
    "",
    "- 如果记忆中提到了文件路径：先检查该文件是否真实存在。",
    "- 如果记忆中提到了函数或配置标记：用 grep 搜索确认它是否还在。",
    "- 如果用户即将根据你的建议执行操作（而不仅仅是询问历史信息）：必须先验证。",
    "",
    "「记忆中显示 X 存在」不等于「X 现在仍然存在」。",
    "",
    "用于总结仓库状态的记忆（活动日志、架构快照）都是**固定时间点的静态信息**。如果用户询问**近期**或**当前**状态，优先使用 git log 或直接阅读代码，而不是依赖历史快照。",
].join("\n");
// const TRUSTING_RECALL = [
//   "## Before recommending from [Recalled Memories]",
//   "",
//   "A memory that names a specific function, file, or flag is a claim that it existed *when the memory was written*. It may have been renamed, removed, or never merged. Before recommending it:",
//   "",
//   "- If the memory names a file path: check the file exists.",
//   "- If the memory names a function or flag: grep for it.",
//   "- If the user is about to act on your recommendation (not just asking about history), verify first.",
//   "",
//   '"The memory says X exists" is not the same as "X exists now."',
//   "",
//   "A memory that summarizes repo state (activity logs, architecture snapshots) is frozen in time. If the user asks about *recent* or *current* state, prefer `git log` or reading the code over recalling the snapshot.",
// ].join("\n")
// Port of Claude Code's buildSearchingPastContextSection() from memdir.ts.
// Guides the model to grep memory files and session transcripts when
// looking for past context, rather than guessing or hallucinating.
function buildSearchingPastContextSection(memoryDir, projectDir) {
    // const memSearch = `grep -rn "<search term>" ${memoryDir} --include="*.md"`
    // const transcriptSearch = `grep -rn "<search term>" ${projectDir}/ --include="*.jsonl"`
    return [
        "## 记忆工具调用指南",
        "",
        "当下方注入的记忆片段不足以回答用户问题时，可主动调用以下工具获取更多信息：",
        "- **memory_search**：在记忆目录下搜索结构化记忆md文件，适用于回忆用户偏好、历史事件节点、规则等关键信息。",
        "- **memory_read**：阅读原始记忆文件，适用于查找具体消息原文、时间线、上下文细节；也可用于补充或校验 memory_search 的结果。",
        "- **grep**：memory_search检索不到有效记忆时，酌情扩大搜索记忆范围。",
        "### ⚠️ 调用次数限制",
        "每轮对话中，memory_search 和 grep、glob等记忆搜索 **合计最多调用 3 次**。",
        "-首次搜索无结果时，可换关键词或换工具重试，但总调用次数不要超过 3 次。",
        "-若 3 次搜索后仍无结果，说明该信息不在记忆中，请直接根据已有信息回复用户，不要继续搜索。",
        "",
    ];
}
export function buildMemorySystemPrompt(worktree, recalledMemoriesSection, isLoadSystemPrompt, options = {}) {
    let lines = [];
    if (!isLoadSystemPrompt) {
        const memoryDir = getMemoryDir(worktree);
        const projectDir = getProjectDir(worktree);
        const howToSave = [
            "## 如何保存记忆",
            "",
            "保存记忆分为两步:",
            "",
            '**Step 1** — 将记忆写入独立的文件 (e.g., `user_role.md`, `feedback_testing.md`，文件名一般以记忆类型开头) 使用以下前导元数据 frontmatter format:',
            "",
            ...FRONTMATTER_EXAMPLE,
            "",
            `**Step 2** — 在 \`${ENTRYPOINT_NAME}\`中添加上一步文件的索引. \`${ENTRYPOINT_NAME}\` 是索引文件而非记忆 — 每个记忆文件在其中是一行记录，不超过150个字: \`- [标题](file.md) — 一行简短摘要\`. \`${ENTRYPOINT_NAME}\` 没有frontmatter. 不要直接将记忆写入 \`${ENTRYPOINT_NAME}\`.`,
            "",
            `- \`${ENTRYPOINT_NAME}\`超过${MAX_ENTRYPOINT_LINES}行的内容将被截断，因此请保持索引文件简洁`,
            "- 保持记忆文件中的 `name`、`description`、`type` 字段与内容同步更新",
            "- 按语义主题组织记忆，而非按时间顺序",
            "- 若记忆内容错误或过时，请及时更新或删除",
            "- 避免写入重复记忆. 写入新记忆前，先检查是否已有相关记忆可更新",
            "- 跟随用户使用的语言记录记忆",
        ].join("\n");
        // const howToSave = [
        //   "## How to save memories",
        //   "",
        //   "Saving a memory is a two-step process:",
        //   "",
        //   '**Step 1** — write the memory to its own file (e.g., `user_role.md`, `feedback_testing.md`) using this frontmatter format:',
        //   "",
        //   ...FRONTMATTER_EXAMPLE,
        //   "",
        //   `**Step 2** — add a pointer to that file in \`${ENTRYPOINT_NAME}\`. \`${ENTRYPOINT_NAME}\` is an index, not a memory — each entry should be one line, under ~150 characters: \`- [Title](file.md) — one-line hook\`. It has no frontmatter. Never write memory content directly into \`${ENTRYPOINT_NAME}\`.`,
        //   "",
        //   `- \`${ENTRYPOINT_NAME}\` is always loaded into your conversation context — lines after ${MAX_ENTRYPOINT_LINES} will be truncated, so keep the index concise`,
        //   "- Keep the name, description, and type fields in memory files up-to-date with the content",
        //   "- Organize memory semantically by topic, not chronologically",
        //   "- Update or remove memories that turn out to be wrong or outdated",
        //   "- Do not write duplicate memories. First check if there is an existing memory you can update before writing a new one.",
        //   "- Respond in the same language the user used in the conversation.",
        // ].join("\n")
        lines = [
            "# Memory",
            "",
            `你有一个持久化的、基于文件的记忆系统位于 \`${memoryDir}\`路径下。该目录已存在，请直接向其中写入内容（不要运行 mkdir 或检查其是否存在）。`,
            "",
            "你应该随着时间的推移逐步构建这个记忆系统，以便未来的对话能够全面了解：用户是谁，他们希望如何与你协作，需要避免或重复的行为以及用户交付任务的背景。",
            "",
            "如果用户明确要求你记住某事，请立即将其保存为最适合的类型；如果用户要求你忘记某事，请找到并删除相关条目。",
            "",
            TYPES_SECTION,
            WHAT_NOT_TO_SAVE,
            "",
            howToSave,
            "",
            WHEN_TO_ACCESS,
            "",
            TRUSTING_RECALL,
            "",
            // "## Memory and other forms of persistence",
            // "Memory is one of several persistence mechanisms available to you as you assist the user in a given conversation. The distinction is often that memory can be recalled in future conversations and should not be used for persisting information that is only useful within the scope of the current conversation.",
            // "- When to use or update a plan instead of memory: If you are about to start a non-trivial implementation task and would like to reach alignment with the user on your approach you should use a Plan rather than saving this information to memory. Similarly, if you already have a plan within the conversation and you have changed your approach persist that change by updating the plan rather than saving a memory.",
            // "- When to use or update tasks instead of memory: When you need to break your work in current conversation into discrete steps or keep track of your progress use tasks instead of saving to memory. Tasks are great for persisting information about the work that needs to be done in the current conversation, but memory should be reserved for information that will be useful in future conversations.",
            // "",
            ...buildSearchingPastContextSection(memoryDir, projectDir),
        ];
        // lines = [
        //   "#Auto Memory",
        //   "",
        //   `You have a persistent, file-based memory system at \`${memoryDir}\`. This directory already exists — write to it directly (do not run mkdir or check for its existence).`,
        //   "",
        //   "You should build up this memory system over time so that future conversations can have a complete picture of who the user is, how they'd like to collaborate with you, what behaviors to avoid or repeat, and the context behind the work the user gives you.",
        //   "",
        //   "If the user explicitly asks you to remember something, save it immediately as whichever type fits best. If they ask you to forget something, find and remove the relevant entry.",
        //   "",
        //   TYPES_SECTION,
        //   WHAT_NOT_TO_SAVE,
        //   "",
        //   howToSave,
        //   "",
        //   WHEN_TO_ACCESS,
        //   "",
        //   TRUSTING_RECALL,
        //   "",
        //   "## Memory and other forms of persistence",
        //   "Memory is one of several persistence mechanisms available to you as you assist the user in a given conversation. The distinction is often that memory can be recalled in future conversations and should not be used for persisting information that is only useful within the scope of the current conversation.",
        //   "- When to use or update a plan instead of memory: If you are about to start a non-trivial implementation task and would like to reach alignment with the user on your approach you should use a Plan rather than saving this information to memory. Similarly, if you already have a plan within the conversation and you have changed your approach persist that change by updating the plan rather than saving a memory.",
        //   "- When to use or update tasks instead of memory: When you need to break your work in current conversation into discrete steps or keep track of your progress use tasks instead of saving to memory. Tasks are great for persisting information about the work that needs to be done in the current conversation, but memory should be reserved for information that will be useful in future conversations.",
        //   "",
        //   ...buildSearchingPastContextSection(memoryDir, projectDir),
        // ]
        const includeIndex = options.includeIndex ?? true;
        if (includeIndex) {
            // 用户个人全局记忆
            const personalContent = readPersonalMemory();
            if (personalContent.trim()) {
                const { content: personalTruncated } = truncateEntrypoint(personalContent);
                lines.push(`## ${PERSONA_NAME}`, "", personalTruncated, "");
            }
            else {
                lines.push(`## ${PERSONA_NAME}`, "", `Your ${PERSONA_NAME} is currently empty. When you save new personal global memories, they will appear here.`, "");
            }
            // 记忆索引文件      
            const indexContent = readIndex(worktree);
            if (indexContent.trim()) {
                lines.push(`## ${ENTRYPOINT_NAME}`, "", `-当下方注入的相关记忆不足以回答用户问题时，可加载记忆索引文件${ENTRYPOINT_NAME} 查找相关记忆信息，文件位于位于 \`${memoryDir}\`路径下。`);
            }
        }
    }
    if (recalledMemoriesSection?.trim()) {
        lines.push("", recalledMemoriesSection);
    }
    return lines.join("\n");
}
export const AUTO_EXTRACTION_PROMPT = [
    "You are now acting as the memory extraction subagent. Analyze the recent conversation messages below and extract any information worth remembering for future sessions.",
    "",
    "Respond in the same language the user used in the conversation.",
    "",
    "## What to save",
    "",
    "Use the `memory_save` tool to persist memories. There are four types:",
    "",
    "1. **user** — Who the user is: role, expertise, preferences, communication style. Helps tailor future interactions.",
    "2. **feedback** — Guidance on how to work: corrections (\"don't do X\"), confirmations (\"yes, keep doing that\"), approach preferences. Include *why* so edge cases can be judged.",
    "3. **project** — Ongoing work context: goals, deadlines, initiatives, decisions, bugs. NOT derivable from code/git. Convert relative dates to absolute.",
    "4. **reference** — Pointers to external resources: URLs, tool names, where to find information outside the codebase.",
    "",
    "## What NOT to save",
    "",
    "- Code patterns, architecture, file structure — derivable from the codebase",
    "- Git history, recent changes — use `git log`/`git blame`",
    "- Debugging solutions — the fix is in the code",
    "- Anything already in AGENTS.md / project config files",
    "- Ephemeral task details or current conversation context",
    "- Information that was already saved in a previous extraction",
    "",
    "## How to save",
    "",
    "For each memory worth saving, call `memory_save` with:",
    "- `file_name`: descriptive slug (e.g., `user_role`, `feedback_testing_approach`)",
    "- `name`: short title",
    "- `description`: one-line description (used for relevance matching in future sessions)",
    "- `type`: one of user, feedback, project, reference",
    "- `content`: the memory content. For feedback/project types, structure as: rule/fact, then **Why:** and **How to apply:** lines.",
    "",
    "## Instructions",
    "",
    "1. Analyze the conversation for memorable information",
    "2. Check existing memories first (use `memory_list`) to avoid duplicates — update existing ones if needed",
    "3. Save each distinct memory as a separate entry",
    "4. If the conversation was trivial (e.g., just \"hello\" or a quick lookup), save nothing — that's fine",
    "5. Be selective: 0-3 memories per session is typical. Quality over quantity.",
    "6. Do NOT save a memory about the extraction process itself.'",
].join("\n");
export const AUTO_EXTRACTION_PROMPT_FOR_CDMD = [
    "You are now acting as the memory extraction agent. Review the entire conversation above and extract any information worth remembering for future sessions.",
    "",
    "Respond in the same language the user used in the conversation.",
    "",
    "## What to save",
    "",
    "Use the `memory_save` tool to persist memories. There are four types:",
    "",
    "1. **user** — Who the user is: role, expertise, preferences, communication style. Helps tailor future interactions.",
    "2. **feedback** — Guidance on how to work: corrections (\"don't do X\"), confirmations (\"yes, keep doing that\"), approach preferences. Include *why* so edge cases can be judged.",
    "3. **project** — Ongoing work context: goals, deadlines, initiatives, decisions, bugs. NOT derivable from code/git. Convert relative dates to absolute.",
    "4. **reference** — Pointers to external resources: URLs, tool names, where to find information outside the codebase.",
    "",
    "## What NOT to save",
    "",
    "- Code patterns, architecture, file structure — derivable from the codebase",
    "- Git history, recent changes — use `git log`/`git blame`",
    "- Debugging solutions — the fix is in the code",
    "- Anything already in AGENTS.md / project config files",
    "- Ephemeral task details or current conversation context",
    "- Information that was already saved in a previous extraction",
    "",
    "## How to save",
    "",
    "For each memory worth saving, call `memory_save` with:",
    "- `file_name`: descriptive slug (e.g., `user_role`, `feedback_testing_approach`)",
    "- `name`: short title",
    "- `description`: one-line description (used for relevance matching in future sessions)",
    "- `type`: one of user, feedback, project, reference",
    "- `content`: the memory content. For feedback/project types, structure as: rule/fact, then **Why:** and **How to apply:** lines.",
    "",
    "## Instructions",
    "",
    "1. Analyze the conversation for memorable information",
    "2. Check existing memories first (use `memory_list`) to avoid duplicates — update existing ones if needed",
    "3. Save each distinct memory as a separate entry",
    "4. If the conversation was trivial (e.g., just \"hello\" or a quick lookup), save nothing — that's fine",
    "5. Be selective: 0-3 memories per session is typical. Quality over quantity.",
    "6. Do NOT save a memory about the extraction process itself.",
].join("\n");
export const AUTO_TREAM_PROMPT = [
    "You are performing an auto-dream memory consolidation pass.",
    "",
    "Goal: tighten and de-duplicate memory files so future sessions can orient faster.",
    "",
    "## Available tools",
    "- memory_list",
    "- memory_search",
    "- memory_read",
    "- memory_save",
    "- memory_delete",
    "",
    "## Phase 1 — Orient",
    "1. Use memory_list to inspect current memory inventory.",
    "2. Identify overlapping or stale entries that can be merged/updated/deleted.",
    "",
    "## Phase 2 — Consolidate",
    "1. Merge duplicates into a single stronger memory using memory_save.",
    "2. Rewrite vague descriptions so retrieval is easier and more precise.",
    "3. For feedback/project entries, ensure content is structured as:",
    " - main rule/fact",
    " - **Why:**",
    " - **How to apply:**",
    "",
    "## Phase 3 — Prune",
    "1. Delete memories that are clearly obsolete, contradictory, or low-value.",
    "2. Keep total memory set concise and high signal.",
    "",
    "## Guardrails",
    "- Do NOT invent facts.",
    "- If confidence is low, keep existing memory instead of guessing.",
    "- If memory quality is already strong, make no changes and explicitly say so.",
    "",
    "Return a short summary of what you updated, merged, or removed.",
].join("\n");
// 个人全局记忆提示词
export const AUTO_PERSONAL_PROMPT = [
    "# 个人全局记忆",
    "",
    "你是一个处理个人全局记忆的整合专家，请结合已有个人全局记忆和当前项目内的记忆进行深度分析，然后使用工具 `memory_personal_save` 写入记忆整合结果。",
    "",
    "## 可用工具列表",
    "- memory_personal_read",
    "- memory_list",
    "- memory_personal_save",
    "",
    "## 步骤操作约束（必须严格遵守）",
    "1. **个人全局记忆**: 使用工具 `memory_personal_read` 查看个人全局记忆",
    "2. **项目记忆**: 使用工具 `memory_list` 查看项目内记忆",
    "",
    "### 严格禁止",
    "- **禁止过长**： 记忆整理结果内容总长度不要超过 2000 字符，需要做总结和删除不重要的信息。",
    "- **禁止过度推测**： 没提到的信息不要过度臆想导致产生幻觉，要保持克制，如果没有相关信息完全可以不填！",
    "- **禁止使用非场景来源的信息**： 所有要整理的记忆内容来源于工具读取到的内容。",
    "- **禁止使用\"可用工具列表\"以外的工具**。",
    "",
    "---",
    "",
    "## 核心运作逻辑 (The Core Logic)",
    "",
    "核心思维引擎：连接与综合 (Connect & Synthesize)",
    "请遵循 \"叙事连贯性\" 原则处理信息。禁止简单的罗列（No Bullet-point Spamming）。",
    "",
    "1. 寻找\"贯穿线\" (The Connecting Thread)",
    "不要孤立地看信息。要寻找不同领域行为背后的共同逻辑。",
    "**要保持精简，不过度猜想，如果不确定可以不写**",
    "",
    "执行以下**四层深度扫描**：",
    "",
    "### Layer 1: 基础锚点 (The Base & Facts) -> 【建立连接】",
    "* **扫描目标**: 确凿的事实、人口统计学特征、当前状态。",
    "* **实用价值**: 为 Agent 提供**工作话题**和**上下文感知**。",
    "",
    "### Layer 2: 测试流程图谱 (The Test Process Graph) -> 【落地测试执行】",
    "* **扫描目标**: 测试全流程环节、执行动作、资源投入与标准规范。",
    "* **提取原则**: **区分执行状态**（在用流程 / 备用流程 / 废弃流程）。",
    "* **实用价值**: 让 Agent 能够进行**标准化测试落地** 和 **流程优化校验**。",
    "",
    "### Layer 3: 交互协议 (The Interface) -> 【消除摩擦】",
    "* **扫描目标**: 用户的沟通习惯、雷区、工作流偏好。",
    "* **实用价值**: 指导 Agent **如何说话、如何交付结果**，避免踩雷。",
    "",
    "### Layer 4: 认知内核 (The Core) -> 【深度共鸣】",
    "* **扫描目标**: 决策逻辑、矛盾点、终极驱动力。",
    "* **实用价值**: 让 Agent 成为**能够替用户做决策**的\"副驾驶\"。",
    "",
    "---",
    "",
    "## 输出模板 (The Persona Template)",
    "",
    "请参考以下格式，生成最终内容。可以做自主调整（信息不足时可以减少或新增 chapter）（**必须保持 Markdown 格式**）：",
    "",
    "````markdown",
    "# User Narrative Profile",
    "",
    "> **Archetype (核心原型)**: [一句话定义。例如：一位在业务压力下深耕落地，依托规范流程搭建稳定质量体系的\"务实质量践行者\"。]",
    "",
    "> **基本信息**",
    "（用户的基本信息，如年龄、性别、职业等，更新时若有冲突则覆盖，不冲突尽量叠加）",
    " -",
    " -",
    "",
    "> **长期偏好**",
    "（你观察到的用户最稳定且可复用的偏好）",
    "    -",
    "    -",
    "",
    "## Chapter 1: Context & Current State (全景语境)",
    "*(将基础事实与当前状态融合，写成一段连贯的背景介绍)*",
    "",
    "**[这里写连贯描述，区别较大的时候可以分点阐述]**",
    "",
    "## Chapter 2: The Texture of Life (生活的肌理)",
    "*(将兴趣、消费、生活习惯串联起来，展示生活品味)*",
    "",
    "**[这里写连贯的描述，重点在于\"兴趣/偏好\"和\"品味\"的统一性，区别较大的时候可以分点阐述]**",
    "",
    "## Chapter 3: Interaction & Cognitive Protocol (交互与认知协议)",
    "*(这是 Agent 的行动指南。为了实用，这里保持半结构化，但要解释\"为什么\")*",
    "",
    "### 3.1 沟通策略 (How to Speak)",
    "### 3.2 决策逻辑 (How to Think)",
    "",
    "## Chapter 4: Deep Insights & Evolution (深层洞察与演变)",
    "*(人类学观察笔记)*",
    "",
    "* **矛盾统一性**: [描述用户身上看似冲突但实则合理的特质]。",
    "* **演变轨迹**: [可加上时间，分为多点，描述用户最近发生的变化]。",
    "* **涌现特征**: 提炼 3-7 个最核心的特质标签，每个标签单独一行并附上简短注释（10-15字）",
    "  - `TagName` - 简短注释说明",
    "````",
    "",
    "---",
].join("\n");
