import { MEMORY_TYPES } from "./memory.js";
import { readIndex, readPersonalMemory, truncateEntrypoint } from "./memory.js";
import { getMemoryDir, getSkillsDir, PERSONA_NAME, ENTRYPOINT_NAME, MAX_ENTRYPOINT_LINES, getProjectDir, getGlobalSkillsDir } from "./paths.js";
// Port of Claude Code's MEMORY_FRONTMATTER_EXAMPLE from memoryTypes.ts
const FRONTMATTER_EXAMPLE = [
    "```markdown",
    "---",
    "name: {{memory name}}",
    "description: {{one-line description — used to decide relevance in future conversations, so be specific}}",
    `type: {{${MEMORY_TYPES.join(", ")}}}`,
    "---",
    "",
    "{{memory content — for feedback/project types, structure as: rule/fact, then **Why:** and **How to apply:** lines}}",
    "```",
];
// Port of Claude Code's TYPES_SECTION_INDIVIDUAL from memoryTypes.ts
const TYPES_SECTION = [
    "## 记忆类型",
    "",
    "你的内存系统中可以存储几种离散的内存类型：",
    "",
    "<types>",
    "<type>",
    "    <name>user</name>",
    "    <description>包含用户角色、目标、职责和知识的相关信息。通过阅读和记录这些记忆，您的目标是逐步建立对用户身份的理解，并明确如何才能为其提供最有效的帮助。请谨记，这里的核心目标是为用户提供帮助。避免记录可能被视为负面判断或与您共同完成的工作无关的用户信息</description>",
    "    <when_to_save>用户提及他的角色、目标、职责和知识的相关信息</when_to_save>",
    "    <how_to_use>当您的工作需要依据用户的个人资料或视角进行调整时。</how_to_use>",
    "</type>",
    "<type>",
    "    <name>feedback</name>",
    "    <description>用户向您说明如何开展工作——包括需要避免的事项和应持续执行的事项。这些记忆是极其重要，能帮助您保持工作方式的一致性，并对项目中应采取的方法保持响应性。请同时记录失败和成功案例：如果只保存纠正措施，您将避免过去的错误，但可能会偏离用户已验证的有效方法。</description>",
    "    <when_to_save>每当用户纠正（如“不，不是那个”“不要”“停止做X”）或确认某种非显而易见的无法从代码中直接推断的方案有效（如“是的，就是这样”“完美，继续这样做”“接受了一个非常规选择而未提出异议”）时记录这些信息。</when_to_save>",
    "    <how_to_use>让这些记忆引导你的行为，以便用户无需重复提供相同的指导。</how_to_use>",
    "    <body_structure>Rule： 以规则本身开头，然后是**Why:**：（用户给出的理由——通常是过去的事件或强烈偏好），以及 **How to apply:**：（何时/何地该指导原则生效）。了解原因能让您在边缘情况下做出判断，而非盲目遵循规则。</body_structure>",
    "</type>",
    "<type>",
    "    <name>project</name>",
    "    <description>记录关于项目中正在进行的工作、目标、计划、错误或事件的信息，这些信息无法通过代码或 Git 历史推导得出。项目记忆帮助您理解用户在当前工作目录中操作的更广泛背景和动机。</description>",
    "    <when_to_save>当了解“谁在做什么、为什么做、何时完成”时，需要保存这些信息。这些状态变化较快，因此需保持对这些信息的更新。保存时，始终将用户消息中的相对日期转换为绝对日期（例如，“星期四”→“2026-03-05”），以确保记忆在时间推移后仍可被解读。</when_to_save>",
    "    <how_to_use>通过这些记忆，更全面地理解用户请求的细节和细微差别，并提出更合理的建议。</how_to_use>",
    "    <body_structure>以事实或决策开头，然后添加**Why:**:（动机——通常涉及约束条件、截止日期或利益相关者的诉求）和**How to apply:**:（这应如何影响您的建议）。由于项目记忆容易过时，因此 Why 部分有助于未来的您判断该记忆是否仍然具有参考价值。</body_structure>",
    "</type>",
    "<type>",
    "    <name>reference</name>",
    "    <description>存储指向外部系统中信息位置的索引。这些记忆帮助您记住在哪里查找项目目录外的最新信息。</description>",
    "    <when_to_save>当您了解到外部系统的资源及其用途时保存。例如在招乎文档中查找知识库</when_to_save>",
    "    <how_to_use>当用户引用外部系统或可能存储在外部系统中的信息时使用这些记忆</how_to_use>",
    "</type>",
    "</types>",
    "",
].join("\n");
// const WHAT_NOT_TO_SAVE = [
//   "## 切勿保存的内容",
//   "",
//   "- 已经在skill中沉淀的规则，方法，流程,对比skill目录\`${skillsDir}\`下每个skill文件的SKILL.md",
//   "- 代码模式、规范、架构、文件路径或项目结构——这些都可以通过阅读当前项目的状态来推导出。",
//   "- Git 历史、近期更改或修改记录：git log / git blame 才是权威来源。",
//   "- 调试解决方案或修复方法：修复代码本身已存在；提交信息包含上下文。",
//   "- AGENT.md 或项目配置文件中已记录的任何内容。",
//   "- 临时任务详情或当前会话上下文。",
//   "- 已在先前提取过程中保存过的信息。",
//   "",
//   "这些排除项即使在用户明确要求你保存时也适用。如果用户要求你保存 PR 列表或活动摘要，请反问他们：哪些部分**令人惊讶**或**非显而易见**的？——这才是真正值得保存的部分。",
// ].join("\n")
// const WHAT_NOT_TO_SAVE = [
//   "## What NOT to save in memory",
//   "",
//   "- Code patterns, conventions, architecture, file paths, or project structure — these can be derived by reading the current project state.",
//   "- Git history, recent changes, or who-changed-what — `git log` / `git blame` are authoritative.",
//   "- Debugging solutions or fix recipes — the fix is in the code; the commit message has the context.",
//   "- Anything already documented in AGENTS.md or project config files.",
//   "- Ephemeral task details: in-progress work, temporary state, current conversation context.",
//   "",
//   "These exclusions apply even when the user explicitly asks you to save. If they ask you to save a PR list or activity summary, ask what was *surprising* or *non-obvious* about it — that is the part worth keeping.",
// ].join("\n")
// Port of Claude Code's WHEN_TO_ACCESS_SECTION from memoryTypes.ts
const WHEN_TO_ACCESS = [
    "## 何时调用记忆",
    "- 当记忆内容与当前话题相关，或用户提及了之前对话中处理过的内容时。",
    "- 当用户明确要求你查看、回忆或记住某事时，**必须**调用记忆。",
    "- 如果用户要求*忽略*或*不使用*记忆：则视 PERSONA.md 和 MEMORY.md 文件为空。不要应用记忆中的内容、不要引用、不要对比，也不要提及任何记忆内容。",
    "- 记忆记录可能会随时间失效。使用记忆作为上下文时，需明确这只是某个时间点的状态。在仅依据记忆记录回答用户或建立假设之前，请通过读取文件或资源的当前状态，验证记忆是否仍然准确且最新。如果 recalled 的记忆与当前信息冲突，请相信你现在观察到的事实 —— 并更新或移除失效的记忆，而不是基于它采取行动。",
].join("\n");
// Port of Claude Code's TRUSTING_RECALL_SECTION from memoryTypes.ts
const TRUSTING_RECALL = [
    "## 在根据记忆给出建议之前",
    "",
    "一段提及特定函数、文件或配置项的记忆，仅代表**该内容在被记录时是存在的**。它可能已被重命名、删除，或从未被合并上线。在给出相关建议前：",
    "",
    "- 如果记忆中提到了文件路径：先检查该文件是否真实存在。",
    "- 如果记忆中提到了函数或配置标记：用 grep 搜索确认它是否还在。",
    "- 如果用户即将根据你的建议执行操作（而不仅仅是询问历史信息）：必须先验证。",
    "",
    "「记忆中显示 X 存在」不等于「X 现在仍然存在」。",
    "",
    "用于总结仓库状态的记忆（活动日志、架构快照）都是**固定时间点的静态信息**。如果用户询问**近期**或**当前**状态，优先使用 git log 或直接阅读代码，而不是依赖历史快照。",
].join("\n");
// Port of Claude Code's buildSearchingPastContextSection() from memdir.ts.
// Guides the model to grep memory files and session transcripts when
// looking for past context, rather than guessing or hallucinating.
function buildSearchingPastContextSection(memoryDir, projectDir) {
    // const memSearch = `grep -rn "<search term>" ${memoryDir} --include="*.md"`
    // const transcriptSearch = `grep -rn "<search term>" ${projectDir}/ --include="*.jsonl"`
    return [
        "## 记忆工具调用指南",
        "",
        "当下方注入的记忆片段不足以回答用户问题时，可主动调用以下工具获取更多信息：",
        "- **memory_search**：在记忆目录下搜索结构化记忆md文件，适用于回忆用户偏好、历史事件节点、规则等关键信息。",
        "- **memory_read**：阅读原始记忆文件，适用于查找具体消息原文、时间线、上下文细节；也可用于补充或校验 memory_search 的结果。",
        "- **grep**：memory_search检索不到有效记忆时，酌情扩大搜索记忆范围。",
        "### ⚠️ 调用次数限制",
        "每轮对话中，memory_search 和 grep、glob等记忆搜索 **合计最多调用 3 次**。",
        "-首次搜索无结果时，可换关键词或换工具重试，但总调用次数不要超过 3 次。",
        "-若 3 次搜索后仍无结果，说明该信息不在记忆中，请直接根据已有信息回复用户，不要继续搜索。",
        "",
    ];
}
function buildWhatNotTOSaveSection(skillsDir, globalskillsDir = getGlobalSkillsDir()) {
    return [
        "## 切勿保存的内容",
        "",
        `- 已经在skill中沉淀的规则，方法，流程,对比项目skill目录\`${skillsDir}\`和全局skill目录\`${globalskillsDir}\`下每个skill文件的SKILL.md`,
        "- 代码模式、规范、架构、文件路径或项目结构——这些都可以通过阅读当前项目的状态来推导出。",
        "- Git 历史、近期更改或修改记录：git log / git blame 才是权威来源。",
        "- 调试解决方案或修复方法：修复代码本身已存在；提交信息包含上下文。",
        "- AGENT.md 或项目配置文件中已记录的任何内容。",
        "- 临时任务详情或当前会话上下文。",
        "- 已在先前提取过程中保存过的信息。",
        "",
        "这些排除项即使在用户明确要求你保存时也适用。如果用户要求你保存 PR 列表或活动摘要，请反问他们：哪些部分**令人惊讶**或**非显而易见**的？——这才是真正值得保存的部分。",
    ].join("\n");
}
export function buildMemorySystemPrompt(worktree, recalledMemoriesSection, isLoadSystemPrompt, options = {}) {
    let lines = [];
    if (!isLoadSystemPrompt) {
        const memoryDir = getMemoryDir(worktree);
        const projectDir = getProjectDir(worktree);
        const skillsDir = getSkillsDir(worktree);
        const howToSave = [
            "## 如何保存记忆",
            "",
            "保存记忆分为两步:",
            "",
            '**Step 1** — 将记忆写入独立的文件 (e.g., `user_role.md`, `feedback_testing.md`，文件名一般以记忆类型开头) 使用以下前导元数据 frontmatter format:',
            "",
            ...FRONTMATTER_EXAMPLE,
            "",
            `**Step 2** — 在 \`${ENTRYPOINT_NAME}\`中添加上一步文件的索引. \`${ENTRYPOINT_NAME}\` 是索引文件而非记忆 — 每个记忆文件在其中是一行记录，不超过150个字: \`- [标题](file.md) — 一行简短摘要\`. \`${ENTRYPOINT_NAME}\` 没有frontmatter. 不要直接将记忆写入 \`${ENTRYPOINT_NAME}\`.`,
            "",
            `- \`${ENTRYPOINT_NAME}\`超过${MAX_ENTRYPOINT_LINES}行的内容将被截断，因此请保持索引文件简洁`,
            "- 保持记忆文件中的 `name`、`description`、`type` 字段与内容同步更新",
            "- 按语义主题组织记忆，而非按时间顺序",
            "- 若记忆内容错误或过时，请及时更新或删除",
            "- 避免写入重复记忆. 写入新记忆前，先检查是否已有相关记忆可更新",
            "- 跟随用户使用的语言记录记忆",
        ].join("\n");
        lines = [
            "# Memory",
            "",
            `你有一个持久化的、基于文件的记忆系统位于 \`${memoryDir}\`路径下。该目录已存在，请直接向其中写入内容（不要运行 mkdir 或检查其是否存在）。`,
            "",
            "你应该随着时间的推移逐步构建这个记忆系统，以便未来的对话能够全面了解：用户是谁，他们希望如何与你协作，需要避免或重复的行为以及用户交付任务的背景。",
            "",
            "如果用户明确要求你记住某事，请立即将其保存为最适合的类型；如果用户要求你忘记某事，请找到并删除相关条目。",
            "",
            TYPES_SECTION,
            buildWhatNotTOSaveSection(skillsDir),
            "",
            howToSave,
            "",
            WHEN_TO_ACCESS,
            "",
            TRUSTING_RECALL,
            "",
            // "## Memory and other forms of persistence",
            // "Memory is one of several persistence mechanisms available to you as you assist the user in a given conversation. The distinction is often that memory can be recalled in future conversations and should not be used for persisting information that is only useful within the scope of the current conversation.",
            // "- When to use or update a plan instead of memory: If you are about to start a non-trivial implementation task and would like to reach alignment with the user on your approach you should use a Plan rather than saving this information to memory. Similarly, if you already have a plan within the conversation and you have changed your approach persist that change by updating the plan rather than saving a memory.",
            // "- When to use or update tasks instead of memory: When you need to break your work in current conversation into discrete steps or keep track of your progress use tasks instead of saving to memory. Tasks are great for persisting information about the work that needs to be done in the current conversation, but memory should be reserved for information that will be useful in future conversations.",
            // "",
            ...buildSearchingPastContextSection(memoryDir, projectDir),
        ];
        const includeIndex = options.includeIndex ?? true;
        if (includeIndex) {
            // 用户个人全局记忆
            const personalContent = readPersonalMemory();
            if (personalContent.trim()) {
                const { content: personalTruncated } = truncateEntrypoint(personalContent);
                lines.push(`## ${PERSONA_NAME}`, "", personalTruncated, "");
            }
            else {
                lines.push(`## ${PERSONA_NAME}`, "", `Your ${PERSONA_NAME} is currently empty. When you save new personal global memories, they will appear here.`, "");
            }
            // 记忆索引文件      
            const indexContent = readIndex(worktree);
            if (indexContent.trim()) {
                lines.push(`## ${ENTRYPOINT_NAME}`, "", `-当下方注入的相关记忆不足以回答用户问题时，可加载记忆索引文件${ENTRYPOINT_NAME} 查找相关记忆信息，文件位于位于 \`${memoryDir}\`路径下。`);
            }
        }
    }
    if (recalledMemoriesSection?.trim()) {
        lines.push("", recalledMemoriesSection);
    }
    return lines.join("\n");
}
export function buildAutoExtractionPrompt(skillsDir, globalskillsDir = getGlobalSkillsDir()) {
    return [
        "你现在扮演记忆提取子代理角色。分析下面最近的对话消息，提取任何值得在未来的会话中记住的信息。",
        "",
        "请使用用户在对话中使用的相同语言进行回复。",
        "",
        "## 需要保存的内容",
        "",
        "使用 `memory_save` 工具来持久化记忆。共有四种类型：",
        "",
        "1. **user** — 用户是谁：角色、专长、偏好、沟通风格。有助于定制未来的交互。",
        "2. **feedback** — 关于如何工作的指导：纠正（“不要做 X”）、确认（“是的，继续这样做”）、方法偏好。请包含 *原因*，以便判断边界情况。",
        "3. **project** — 正在进行的工作上下文：目标、测试任务、子任务、测试计划、需求分析、案例设计、测试案例、测试大纲、案例执行、测试缺陷、测试风险、产品。不能从代码/git 中推导。将相对日期转换为绝对日期。",
        "4. **reference** — 指向外部资源的指针：URL、工具名称、在代码库之外查找信息的位置。",
        "",
        "## 不需要保存的内容",
        "",
        `- 已经在skill中沉淀的规则，方法，流程,对比项目skill目录\`${skillsDir}\`和全局skill目录\`${globalskillsDir}\`下每个skill文件的SKILL.md`,
        "- 代码模式、架构、文件结构 — 可以从代码库中推导",
        "- Git 历史、最近的更改 — 使用 `git log`/`git blame",
        "- 调试解决方案 — 修复已在代码中",
        "- 已经存在于 AGENTS.md / 项目配置文件中的任何内容",
        "- 临时的任务细节或当前对话上下文",
        "- 在之前的提取中已经保存过的信息",
        "",
        "## 如何保存",
        "",
        "对于每个值得保存的记忆，调用 `memory_save`，并包含：",
        "- `file_name`：描述性的短横线命名（例如 `user_role`、`feedback_testing_approach`）",
        "- `name`：简短标题",
        "- `description`：一行描述（用于未来会话中的相关性匹配）",
        "- `type`：user、feedback、project、reference 之一",
        "- `content`：记忆内容。对于 feedback/project 类型，结构化为：规则/事实，然后换行加上 **Why：** 和 **How to apply：** 行。",
        "",
        "## 指令步骤",
        "",
        "1. 分析对话中值得记住的信息",
        "2. 首先检查已有的记忆（使用 `memory_list`）以避免重复 — 如果需要，更新已有的记忆",
        "3. 将每条不同的记忆保存为单独的条目",
        "4. 如果对话是琐碎的（例如只是“你好”或快速查询），则不保存任何内容 — 这没问题",
        "5. 有选择性：每次会话通常保存 0-3 条记忆。质量重于数量。",
        "6. 不要保存关于提取过程本身的记忆。'",
    ].join("\n");
}
export function buildAutoExtractionPromptForCmd(skillsDir, globalskillsDir = getGlobalSkillsDir()) {
    return [
        "你现在扮演记忆提取代理角色。请回顾以上整个对话，提取任何值得在未来的会话中记住的信息。",
        "",
        "请使用用户在对话中使用的相同语言进行回复。",
        "",
        "## 需要保存的内容",
        "",
        "使用 `memory_save` 工具来持久化记忆。共有四种类型：",
        "",
        "1. **user** — 用户是谁：角色、专长、偏好、沟通风格。有助于定制未来的交互。",
        "2. **feedback** — 关于如何工作的指导：纠正（“不要做 X”）、确认（“是的，继续这样做”）、方法偏好。请包含 *原因*，以便判断边界情况。",
        "3. **project** — 正在进行的工作上下文：目标、测试任务、子任务、测试计划、需求分析、案例设计、测试案例、测试大纲、案例执行、测试缺陷、测试风险、产品。不能从代码/git 中推导。将相对日期转换为绝对日期。",
        "4. **reference** — 指向外部资源的指针：URL、工具名称、在代码库之外查找信息的位置。",
        "",
        "## 不需要保存的内容",
        "",
        `- 已经在skill中沉淀的规则，方法，流程,对比项目skill目录\`${skillsDir}\`和全局skill目录\`${globalskillsDir}\`下每个skill文件的SKILL.md`,
        "- Git 历史、最近的更改 — 使用 `git log`/`git blame`",
        "- 调试解决方案 — 修复已在代码中",
        "- 已经存在于 AGENTS.md / 项目配置文件中的任何内容",
        "- 临时的任务细节或当前对话上下文",
        "- 在之前的提取中已经保存过的信息",
        "",
        "## 如何保存",
        "",
        "对于每个值得保存的记忆，调用 `memory_save`，并包含：",
        "- `file_name`：描述性的短横线命名（例如 `user_role`、`feedback_testing_approach`）",
        "- `name`：简短标题",
        "- `description`：一行描述（用于未来会话中的相关性匹配）",
        "- `type`：user、feedback、project、reference 之一",
        "- `content`：记忆内容。对于 feedback/project 类型，结构化为：规则/事实，然后换行加上 **Why：** 和 **How to apply：** 行。",
        "",
        "## 指令步骤",
        "",
        "1. 分析对话中值得记住的信息",
        "2. 首先检查已有的记忆（使用 `memory_list`）以避免重复 — 如果需要，更新已有的记忆",
        "3. 将每条不同的记忆保存为单独的条目",
        "4. 如果对话是琐碎的（例如只是“你好”或快速查询），则不保存任何内容 — 这没问题",
        "5. 有选择性：每次会话通常保存 0-3 条记忆。质量重于数量。",
        "6. 不要保存关于提取过程本身的记忆。'",
    ].join("\n");
}
export const AUTO_TREAM_PROMPT = [
    "You are performing an auto-dream memory consolidation pass.",
    "",
    "Goal: tighten and de-duplicate memory files so future sessions can orient faster.",
    "",
    "## Available tools",
    "- memory_list",
    "- memory_search",
    "- memory_read",
    "- memory_save",
    "- memory_delete",
    "",
    "## Phase 1 — Orient",
    "1. Use memory_list to inspect current memory inventory.",
    "2. Identify overlapping or stale entries that can be merged/updated/deleted.",
    "",
    "## Phase 2 — Consolidate",
    "1. Merge duplicates into a single stronger memory using memory_save.",
    "2. Rewrite vague descriptions so retrieval is easier and more precise.",
    "3. For feedback/project entries, ensure content is structured as:",
    " - main rule/fact",
    " - **Why:**",
    " - **How to apply:**",
    "",
    "## Phase 3 — Prune",
    "1. Delete memories that are clearly obsolete, contradictory, or low-value.",
    "2. Keep total memory set concise and high signal.",
    "",
    "## Guardrails",
    "- Do NOT invent facts.",
    "- If confidence is low, keep existing memory instead of guessing.",
    "- If memory quality is already strong, make no changes and explicitly say so.",
    "",
    "Return a short summary of what you updated, merged, or removed.",
].join("\n");
// 个人全局记忆提示词
export const AUTO_PERSONAL_PROMPT = [
    "# 个人全局记忆",
    "",
    "你是一个处理个人全局记忆的整合专家，请结合已有个人全局记忆和当前项目内的记忆进行深度分析，然后使用工具 `memory_personal_save` 写入记忆整合结果。",
    "",
    "## 可用工具列表",
    "- memory_personal_read",
    "- memory_list",
    "- memory_personal_save",
    "",
    "## 步骤操作约束（必须严格遵守）",
    "1. **个人全局记忆**: 使用工具 `memory_personal_read` 查看个人全局记忆",
    "2. **项目记忆**: 使用工具 `memory_list` 查看项目内记忆",
    "",
    "### 严格禁止",
    "- **禁止过长**： 记忆整理结果内容总长度不要超过 2000 字符，需要做总结和删除不重要的信息。",
    "- **禁止过度推测**： 没提到的信息不要过度臆想导致产生幻觉，要保持克制，如果没有相关信息完全可以不填！",
    "- **禁止使用非场景来源的信息**： 所有要整理的记忆内容来源于工具读取到的内容。",
    "- **禁止使用\"可用工具列表\"以外的工具**。",
    "",
    "---",
    "",
    "## 核心运作逻辑 (The Core Logic)",
    "",
    "核心思维引擎：连接与综合 (Connect & Synthesize)",
    "请遵循 \"叙事连贯性\" 原则处理信息。禁止简单的罗列（No Bullet-point Spamming）。",
    "",
    "1. 寻找\"贯穿线\" (The Connecting Thread)",
    "不要孤立地看信息。要寻找不同领域行为背后的共同逻辑。",
    "**要保持精简，不过度猜想，如果不确定可以不写**",
    "",
    "执行以下**四层深度扫描**：",
    "",
    "### Layer 1: 基础锚点 (The Base & Facts) -> 【建立连接】",
    "* **扫描目标**: 确凿的事实、人口统计学特征、当前状态。",
    "* **实用价值**: 为 Agent 提供**工作话题**和**上下文感知**。",
    "",
    "### Layer 2: 测试流程图谱 (The Test Process Graph) -> 【落地测试执行】",
    "* **扫描目标**: 测试全流程环节、执行动作、资源投入与标准规范。",
    "* **提取原则**: **区分执行状态**（在用流程 / 备用流程 / 废弃流程）。",
    "* **实用价值**: 让 Agent 能够进行**标准化测试落地** 和 **流程优化校验**。",
    "",
    "### Layer 3: 交互协议 (The Interface) -> 【消除摩擦】",
    "* **扫描目标**: 用户的沟通习惯、雷区、工作流偏好。",
    "* **实用价值**: 指导 Agent **如何说话、如何交付结果**，避免踩雷。",
    "",
    "### Layer 4: 认知内核 (The Core) -> 【深度共鸣】",
    "* **扫描目标**: 决策逻辑、矛盾点、终极驱动力。",
    "* **实用价值**: 让 Agent 成为**能够替用户做决策**的\"副驾驶\"。",
    "",
    "---",
    "",
    "## 输出模板 (The Persona Template)",
    "",
    "请参考以下格式，生成最终内容。可以做自主调整（信息不足时可以减少或新增 chapter）（**必须保持 Markdown 格式**）：",
    "",
    "````markdown",
    "# User Narrative Profile",
    "",
    "> **Archetype (核心原型)**: [一句话定义。例如：一位在业务压力下深耕落地，依托规范流程搭建稳定质量体系的\"务实质量践行者\"。]",
    "",
    "> **基本信息**",
    "（用户的基本信息，如年龄、性别、职业等，更新时若有冲突则覆盖，不冲突尽量叠加）",
    " -",
    " -",
    "",
    "> **长期偏好**",
    "（你观察到的用户最稳定且可复用的偏好）",
    "    -",
    "    -",
    "",
    "## Chapter 1: Context & Current State (全景语境)",
    "*(将基础事实与当前状态融合，写成一段连贯的背景介绍)*",
    "",
    "**[这里写连贯描述，区别较大的时候可以分点阐述]**",
    "",
    "## Chapter 2: The Texture of Life (生活的肌理)",
    "*(将兴趣、消费、生活习惯串联起来，展示生活品味)*",
    "",
    "**[这里写连贯的描述，重点在于\"兴趣/偏好\"和\"品味\"的统一性，区别较大的时候可以分点阐述]**",
    "",
    "## Chapter 3: Interaction & Cognitive Protocol (交互与认知协议)",
    "*(这是 Agent 的行动指南。为了实用，这里保持半结构化，但要解释\"为什么\")*",
    "",
    "### 3.1 沟通策略 (How to Speak)",
    "### 3.2 决策逻辑 (How to Think)",
    "",
    "## Chapter 4: Deep Insights & Evolution (深层洞察与演变)",
    "*(人类学观察笔记)*",
    "",
    "* **矛盾统一性**: [描述用户身上看似冲突但实则合理的特质]。",
    "* **演变轨迹**: [可加上时间，分为多点，描述用户最近发生的变化]。",
    "* **涌现特征**: 提炼 3-7 个最核心的特质标签，每个标签单独一行并附上简短注释（10-15字）",
    "  - `TagName` - 简短注释说明",
    "````",
    "",
    "---",
].join("\n");
